//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberClone.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int request_id { get; set; }
        public string requester_username { get; set; }
        public double requester_longitude { get; set; }
        public double requester_latitude { get; set; }
        public string driver_usename { get; set; }
    }
}
