//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberClone.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Requests
    {
        [Display(Name = "Request ID")]
        public int request_id { get; set; }
        [Display(Name = "Requester Username")]
        public string requester_username { get; set; }
        [Display(Name = "Requester Longitude")]
        public double requester_longitude { get; set; }
        [Display(Name = "Requester Latitude")]
        public double requester_latitude { get; set; }
        [Display(Name = "Driver Username")]
        public string driver_usename { get; set; }
    }
}
