//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberClone.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [Display(Name = "User ID")]
        public int user_id { get; set; }
        [Display(Name = "Username")]
        public string username { get; set; }
        [Display(Name = "UserType")]
        public string usertype { get; set; }
        [Display(Name = "User Longitude")]
        public Nullable<double> user_longitude { get; set; }
        [Display(Name = "User Latitude")]
        public Nullable<double> user_latitude { get; set; }
    }
}
