//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberClone.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string usertype { get; set; }
        public Nullable<double> user_longitude { get; set; }
        public Nullable<double> user_latitude { get; set; }
    }
}
